name: Backend Build
on:
  workflow_call:
jobs:
  BuildAndReleaseAzure:
    if: "!contains(github.ref_name, '-AWS')"
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    steps:
      - name: Add hosts to /etc/hosts
        run: |
            echo "52.211.28.190 software.r3.com" | tee -a /etc/hosts

      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: false   #set-safe-directory option of checkout didn't work
          fetch-depth: 0
          token: ${{ secrets.B2P_GIT_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.B2P_GIT_USER }}
          git config --global user.email ${{ secrets.B2P_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: CheckCRCSubmodule
        run: |
          echo "Check central-common"
          if cat .gitmodules | grep central-common > /dev/null ; then
            rm -rf central-common
            git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common central-common
            echo -e "\e[92m central-common is added \e[0m"
          else
            echo -e "\e[31m central-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckB2PSubmodule
        run: |
          echo "Check b2p-common"
          if cat .gitmodules | grep b2p-common > /dev/null ; then
            rm -rf b2p-common
            git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
            echo -e "\e[92m b2p-common is added \e[0m"
          else
            echo -e "\e[31m b2p-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckSubmoduleExited
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".gitmodules"

      - name: UpdateSubmodule
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}
          
      - name: RemoveFilesBeforeBuild
        run:
          rm -rf ./src/main/resources/application.yml
          rm -rf ./src/main/resources/application.properties

##### CodeScan
      # - name: SonarQubeScan
      #   # if: contains(github.ref_name, 'SONAR')
      #   if: github.ref_type == 'tag' && contains(github.ref_name, 'SONAR')
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.B2P_SONARQUBE_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.B2P_SONARQUBE_HOST_URL }}
      #     LC_ALL: "en_US.UTF-8"
      #   with:
      #     projectBaseDir: src
      #     args: >
      #       -Dsonar.projectName=B2P-${{ secrets.B2P_SERVICENAME }}
      #       -Dsonar.projectKey=B2P-${{ secrets.B2P_SERVICENAME }}
      #       -Dsonar.projectVersion=${{ github.ref_name }}

      - name: SonarQubeScan
        # if: contains(github.ref_name, 'SONAR')
        if: github.ref_type == 'tag' && contains(github.ref_name, 'SONAR')
        run:
          ./gradlew sonarqube -Dsonar.login=${{ secrets.B2P_SONARQUBE_TOKEN }} -Dsonar.projectName=B2P-${{ secrets.B2P_SERVICENAME }} -Dsonar.projectKey=B2P-${{ secrets.B2P_SERVICENAME }} -Dsonar.projectVersion=${{ github.ref_name }}

      - name: BuildImage
        uses: gradle/gradle-build-action@v2
        if: "!contains(github.ref_name, 'SONAR')"
        with:
          gradle-version: 7.2
          arguments: |
              jib
              --image=${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}

  BuildAndReleaseAWS:
    if: contains(github.ref_name, '-AWS')
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    steps:
      - name: Add hosts to /etc/hosts
        run: |
            echo "52.211.28.190 software.r3.com" | tee -a /etc/hosts

      - name: AddAPK
        run: apk --no-cache add git jq tar openssh docker

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: false   #set-safe-directory option of checkout didn't work
          fetch-depth: 0
          token: ${{ secrets.B2P_GIT_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.B2P_GIT_USER }}
          git config --global user.email ${{ secrets.B2P_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: CheckCRCSubmodule
        run: |
          echo "Check central-common"
          if cat .gitmodules | grep central-common > /dev/null ; then
            rm -rf central-common
            git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common central-common
            echo -e "\e[92m central-common is added \e[0m"
          else
            echo -e "\e[31m central-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckB2PSubmodule
        run: |
          echo "Check b2p-common"
          if cat .gitmodules | grep b2p-common > /dev/null ; then
            rm -rf b2p-common
            git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
            echo -e "\e[92m b2p-common is added \e[0m"
          else
            echo -e "\e[31m b2p-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckSubmoduleExited
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".gitmodules"

      - name: UpdateSubmodule
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: DockerLoginAzure
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}

      - name: DockerLoginAWS
        uses: aws-actions/amazon-ecr-login@v1

      - name: RemoveFilesBeforeBuild
        run:
          rm -rf ./src/main/resources/application.yml
          rm -rf ./src/main/resources/application.properties

      - name: BuildImage (non-customBuyer)
        uses: gradle/gradle-build-action@v2
        # if: "!contains(${{ secrets.B2P_SERVICENAME }}, 'custom_buyer')"
        with:
          gradle-version: 7.2
          arguments: |
              jib
              --image=${{ secrets.B2P_AWS_REGISTRY }}/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}

      # - name: BuildImage (customBuyer)
      #   uses: gradle/gradle-build-action@v2
      #   # if: contains(${{ secrets.B2P_SERVICENAME }}, 'custom_buyer')
      #   with:
      #     gradle-version: 7.2
      #     arguments: |
      #         jib
      #         --image=${{ secrets.B2P_AWS_REGISTRY }}/custom_buyer:${{ github.ref_name }}
