on:
  workflow_call:
jobs:
  BuildAndRelease:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          # path: 'test'
          # submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: DEBUG
        run: |
          echo $GITHUB_WORKSPACE
          find /__w
          # exit 1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.B2P_GIT_USER }}
          git config --global user.email ${{ secrets.B2P_GIT_USER }}@dv.co.th
          ENV=$GITHUB_WORKSPACE; git config --global --add safe.directory $ENV
          # git config --global --add safe.directory /__w/b2p-${{ secrets.B2P_SERVICENAME }}/b2p-${{ secrets.B2P_SERVICENAME }}

      - name: GitSubmodule
        run: |
          rm -rf b2p-common
          git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}
          
      - name: BuildImage
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: |
              jib
              --image=${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}
