on:
  workflow_call:
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, b2p]
    container: openjdk:17-jdk-alpine3.14
    steps:
      - uses: actions/checkout@v3
      - name: AddGIT
        run: apk --no-cache add git
      - run: git config --global --add safe.directory /__w/b2p-${{ secrets.B2P_SERVICENAME }}/b2p-${{ secrets.B2P_SERVICENAME }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.B2P_GIT_TOKEN }}
      - name: GitSubmodule
        run: |
          rm -rf b2p-common
          git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common.git b2p-common 
          git submodule update --remote -f --init
          git submodule add --force --name b2p-common https://github.com/digital-ventures/b2p-common.git b2p-common 
      - name: SetupGradle
        uses: gradle/gradle-build-action@v2
        # with:
        #   gradle-version: 8.0
      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}
      - name: BuildImage
        # if: "!contains(github.ref_name, 'SONAR')"
        run: |
          ./gradlew jib --image=${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}
          echo -e "\e[92m ${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }} \e[0m"
