on:
  workflow_call:
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-alpine3.14
    steps:
      - uses: actions/checkout@v3
      - name: AddGIT
        run: apk --no-cache add git
      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}
      - name: BuildImage
        # if: "!contains(github.ref_name, 'SONAR')"
        run: ./gradlew jib --image=${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}

