on:
  workflow_call:
jobs:
  Test:
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-alpine3.14
    steps:
      - uses: actions/checkout@v3
      - name: Add APK
        run: apk --no-cache add git
      - run: git config --global --add safe.directory /__w/b2p-${{ secrets.B2P_SERVICENAME }}/b2p-${{ secrets.B2P_SERVICENAME }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.B2P_GIT_TOKEN }}
      - name: Git Submodule
        run: |
          git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common.git b2p-common 
          git submodule update --remote -f --init
          git submodule add --force --name b2p-common https://github.com/digital-ventures/b2p-common.git b2p-common 
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}
      - name: SonarQubeScan
        # if: contains(github.ref_name, 'SONAR')
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.B2P_SONARQUBE_TOKEN }} -Dsonar.projectName=${{ github.ref_name }} -Dsonar.projectKey=${{ secrets.SERVICENAME }}
      - name: CleanTest
        run: |
          apk add --no-cache ttf-dejavu fontconfig 
          ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
          LD_LIBRARY_PATH=/usr/lib
          ./gradlew clean test

