on:
  workflow_call:
jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, crc]
    container: node:16.13.0-alpine
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          # submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.B2P_GIT_USER }}
          git config --global user.email ${{ secrets.B2P_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: SetupDockerBuildx
        uses: docker/setup-buildx-action@v2

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}

      - name: BuildAndPush
        if: "!contains(github.ref_name, 'SONAR')"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}
          # ssh: |
          #   default=${{ secrets.SSH_PRIVATE_KEY }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.B2P_GIT_TOKEN }}

      - name: PrepareSteps (approvalui)
        if: "!contains(github.ref_name, 'SONAR') && contains(github.repository, 'admin-portal-ui')"
        run: |
          ./prepare-approval-files.sh

      - name: BuildAndPush (approvalui)
        if: "!contains(github.ref_name, 'SONAR') && contains(github.repository, 'admin-portal-ui')"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.B2P_ACR_REGISTRY }}/b2p/approvalui:${{ github.ref_name }}
          # ssh: |
          #   default=${{ env.SSH_AUTH_SOCK }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.B2P_GIT_TOKEN }}

      - name: BuildAndPushWithCodeScan
        if: "contains(github.ref_name, 'SONAR')"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: DockerfileSonarqube
          build-args: SONARQUBE_TOKEN=${{ secrets.B2P_SONARQUBE_TOKEN }}, CI_COMMIT_TAG=${{ github.ref_name }}
          push: true
          tags: ${{ secrets.B2P_ACR_REGISTRY }}/b2p/${{ secrets.B2P_SERVICENAME }}:${{ github.ref_name }}
